[DEN-258] Create external cli project using cobra and viper
EdgeCast/ec-cli pull request #4
Opened 2022-03-16 15:21 UTC by ssaluja4

2022-03-16 17:25 UTC, stevenpaz commented on cmd/root.go
> +Copyright © 2022 NAME HERE <EMAIL ADDRESS>
We should fill out this placeholder copyright line

2022-03-21 21:48 UTC, defstream requested changes

2022-03-21 21:48 UTC, defstream commented on cmd/root.go
> +		os.Exit(1)
The error should be logged log.Fatal(err), which will print and exit with an error code of 1.

2022-03-21 21:48 UTC, defstream commented on main.go
> +// Copyright 2021 Edgecast Inc., Licensed under the terms of the Apache 2.0 license.
Update to 2022

2022-03-21 22:21 UTC, ssaluja4 commented on cmd/root.go
> +		os.Exit(1)
Updated. thanks.

2022-03-21 22:21 UTC, ssaluja4 commented on main.go
> +// Copyright 2021 Edgecast Inc., Licensed under the terms of the Apache 2.0 license.
Updated. Thanks.

2022-03-22 17:35 UTC, defstream approved these changes

2022-03-22 17:45 UTC, merged